//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSharingSite.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogSharingEntities : DbContext
    {
        public BlogSharingEntities()
            : base("name=BlogSharingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_Blogs> TBL_Blogs { get; set; }
        public virtual DbSet<TBL_Categories> TBL_Categories { get; set; }
        public virtual DbSet<TBL_Comments> TBL_Comments { get; set; }
        public virtual DbSet<TBL_About> TBL_About { get; set; }
        public virtual DbSet<TBL_Messages> TBL_Messages { get; set; }
        public virtual DbSet<TBL_Files> TBL_Files { get; set; }
        public virtual DbSet<TBL_AdminInfo> TBL_AdminInfo { get; set; }
    }
}
