//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSharingSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Messages
    {
        public int messageID { get; set; }
        public string senderName { get; set; }
        public string senderMail { get; set; }
        public string messageSubject { get; set; }
        public string messageContent { get; set; }
        public Nullable<bool> messageStatus { get; set; }
        public Nullable<System.DateTime> messageDate { get; set; }
    }
}
