//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSharingSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TBL_Blogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Blogs()
        {
            this.TBL_Comments = new HashSet<TBL_Comments>();
        }
    
        public int blogID { get; set; }
        public string blogTitle { get; set; }
        [AllowHtml]
        public string blogContent { get; set; }
        public string blogImage { get; set; }
        public Nullable<byte> blogCategory { get; set; }
        public Nullable<System.DateTime> blogDate { get; set; }
        public Nullable<bool> blogStatus { get; set; }
        public Nullable<int> blogViewCount { get; set; }
    
        public virtual TBL_Categories TBL_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Comments> TBL_Comments { get; set; }
    }
}
