//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSharingSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_About
    {
        public byte aboutID { get; set; }
        public string aboutContent { get; set; }
        public string aboutImage { get; set; }
    }
}
